### ISSUE TITLE
gdm gui login freezes

### ISSUE THREAD

**Issue by tester1969** [williamwlk/my-red-corner#1]
cannot login from gui, everything else works. i see that compare.py stays with 100% CPU

**Comment by williamwlk** [comment]
Sorry for the delay in response. 

So Installation {1..4} was good? Tell me more about your setup?

**Comment by tester1969** [comment]
Weird, I was under the impression that I have closed this... The issue was with selinux. 
Anyway, though su, sudo etc worked, it didn't work from gui and after screen lock. I noticed issues in auth logging with selinux. Now it is solved and works fine 
RHEL 7.7, gnome 3.28

**Comment by williamwlk** [comment]
Glad you got it sorted and thanks for letting me know about this.
